# Generated by Django 2.0.2 on 2018-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('arrival', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('train_name', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=50)),
                ('station_code', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_number', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=50)),
            ],
        ),
    ]
