# Generated by Django 2.0.2 on 2018-03-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=50)),
                ('ostation', models.CharField(max_length=50)),
                ('dstation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Trains',
        ),
        migrations.AddField(
            model_name='routestation',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Station'),
        ),
    ]
