# Generated by Django 2.0.2 on 2018-03-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180320_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('tno', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('rid', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='routestation',
            name='tno',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='home.Trains'),
            preserve_default=False,
        ),
    ]
