# Generated by Django 2.0.2 on 2018-03-20 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180320_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestation',
            name='atime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestation',
            name='order',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
