# Generated by Django 2.0.2 on 2018-04-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180320_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='atime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trains',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Route'),
        ),
        migrations.AlterField(
            model_name='trains',
            name='tno',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
