# Generated by Django 2.0.2 on 2018-04-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180410_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('nos', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('cls', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pnr', models.CharField(max_length=50)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Trains')),
            ],
        ),
    ]
