# Generated by Django 2.0.2 on 2018-04-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_payment_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cancel',
            field=models.CharField(max_length=50),
        ),
    ]
