# Generated by Django 2.0.2 on 2018-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20180318_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
