# Generated by Django 2.0.2 on 2018-03-18 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0003_auto_20180318_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='email',
        ),
        migrations.RemoveField(
            model_name='members',
            name='password',
        ),
        migrations.RemoveField(
            model_name='members',
            name='username',
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
