# Generated by Django 2.0.2 on 2018-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0006_delete_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
